// <auto-generated />
using System;
using FutureVendWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureVendWeb.Migrations
{
    [DbContext(typeof(VendingDbContext))]
    [Migration("20250506173952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FutureVendWeb.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.CustomerVendingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("VendingProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VendingProductId");

                    b.ToTable("CustomerVendingProducts");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AcceptCard")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AcceptCash")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("LocationLat")
                        .HasColumnType("double");

                    b.Property<double>("LocationLon")
                        .HasColumnType("double");

                    b.Property<int>("PaymentDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentDeviceSerial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VendingDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("VendingDeviceSerial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentDeviceId");

                    b.HasIndex("VendingDeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.PaymentDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Chip")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NFC")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PaymentDevices");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VendingProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("VendingProductId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.VendingDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SoftwareVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VendingDevices");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.VendingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PLU")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VendingProducts");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.CustomerVendingProduct", b =>
                {
                    b.HasOne("FutureVendWeb.Data.Entities.Customer", "Customer")
                        .WithMany("CustomerVendingProducts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureVendWeb.Data.Entities.VendingProduct", "VendingProduct")
                        .WithMany("CustomerVendingProducts")
                        .HasForeignKey("VendingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("VendingProduct");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.Device", b =>
                {
                    b.HasOne("FutureVendWeb.Data.Entities.Customer", "Customer")
                        .WithMany("Devices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureVendWeb.Data.Entities.PaymentDevice", "PaymentDevice")
                        .WithMany("Devices")
                        .HasForeignKey("PaymentDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureVendWeb.Data.Entities.VendingDevice", "VendingDevice")
                        .WithMany("Devices")
                        .HasForeignKey("VendingDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("PaymentDevice");

                    b.Navigation("VendingDevice");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.Transaction", b =>
                {
                    b.HasOne("FutureVendWeb.Data.Entities.Device", "Device")
                        .WithMany("Transactions")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FutureVendWeb.Data.Entities.VendingProduct", "VendingProduct")
                        .WithMany("Transactions")
                        .HasForeignKey("VendingProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("VendingProduct");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.Customer", b =>
                {
                    b.Navigation("CustomerVendingProducts");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.Device", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.PaymentDevice", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.VendingDevice", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("FutureVendWeb.Data.Entities.VendingProduct", b =>
                {
                    b.Navigation("CustomerVendingProducts");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
